# Generated by Django 5.2.3 on 2025-07-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.company'),
        ),
    ]
