# Generated by Django 5.2.3 on 2025-06-30 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universitycourse',
            name='unique course and semester',
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='polls.course'),
        ),
        migrations.AlterField(
            model_name='universitycourse',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='polls.university'),
        ),
        migrations.AddConstraint(
            model_name='universitycourse',
            constraint=models.UniqueConstraint(fields=('course', 'semester', 'university'), name='unique course and semester'),
        ),
    ]
