# Generated by Django 5.2.3 on 2025-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_universitycourse_unique_course_and_semester_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universitycourse',
            name='unique course and semester',
        ),
        migrations.AddConstraint(
            model_name='universitycourse',
            constraint=models.UniqueConstraint(fields=('course', 'semester', 'university'), name='unique course and semester and university'),
        ),
    ]
